### ISSUE TITLE
Ferramentas manuais de edição

### ISSUE THREAD

**Issue by dinizime** [1cgeo/plugin_edicao#12]
- [x] **Botão:  Alternar visibilidade**

Alterna o atributo visivel das feições selecionadas na camada ativa.

1 -> 2
2 -> 1
9999 -> 1

Erro para o usuário se a camada ativa não tiver o atributo visivel.

- [x] **Botão: Alternar justificativa do texto**

Altenar o atributo justificativa_txt das feições selecionadas na camada ativa.

9999 -> 1
1 -> 2
2 -> 3
3 -> 1

Erro para o usuário se a camada ativa não tiver o atributo justificativa_txt.

- [x] **Botão: Inserir Símbolo de Vegetação**

É uma ferramenta de aquisição exclusiva para edicao_simb_vegetacao_p. Ela deve cruzar o ponto adquirido com cobter_vegetacao_a

Baseado no atributo tipo de cobter_vegetacao_a deve ser preenchido o atributo "texto_edicao" de edicao_simb_vegetacao_p.

1296 -> Ref

801 -> Caat

501 -> Campnr

701 -> Cerr

401 -> Rest

Caso não intersecte uma vegetação que deva gerar texto exibir um erro para o usuário.

A ferramenta deve tornar a camada edicao_simb_vegetacao_p ativa

- [x] **Botão: Inserir Identificador Trecho Rodoviário**

Tambem tem que ter um combo box de "Carta:" com valores "Principal" e "Mini" 

Ideia da ferramenta é procurar a infra_via_deslocamento_l mais próxima do click (talvez uma tolerância) e inserir um edicao_identificador_trecho_rod_p. E a ferramenta verifica se o atributo "sigla" é não nulo e insere o ponto na via de deslocamento.

Se for nulo retorna uma mensagem para o usuário dizendo que a rodovia não possui sigla.

Se não for nulo e tiver ";" no seu valor significa que a rodovia possui multiplas siglas, assim dar split pelo ; e apresentar num combo box para o usuário escolher qual sigla ele quer. No caso de não tiver o ; não precisa desse combo box.

A ferramenta inser um edicao_identificador_trecho_rod_p configurando a sigla (somente o numero, quebrando no "-" a segunda parte) , o valor da jurisdicao (conforme a rodovia) carta_simbolizacao conforme o combo box.

- [x] **Botão: Copiar para texto genérico**

Copia a feição ponto ou linha selecionada (da camada ativa) para a classe edicao_texto_generico_p ou edicao_texto_generico_l conforme a primitiva geometrica.
texto_edicao = "nome" da feição

estilo_fonte = 'Condensed'

tamanho_txt = 6

justificativa_txt = 2

espacamento = 0

cor = ' #000000'

carta_simbolizacao = combo box de carta de simbolização (Principal = 1, Mini = 2)

Se não tiver o atributo "nome" apresentar um erro. Nome não deve ser nulo.

- [x] **Botão: Rótulo de Lago**

Deve ter um poligono de cobter_massa_dagua_a proximo com tipo in (3, 4, 5, 6, 7, 11) e nome não nulo.

Procura a massa dagua mais proxima com uma tolerancia.

É uma ferramenta de aquisição ponto que adiciona na camada edicao_texto_generico_p preenchendo atributos. Insere na posição do click

Deve ter um combo box na própria barra para escolher a escala de trabalho (conforme já está na versão atual do Ferramentas Experimentais), que serve para todo o plugin.

texto_edicao = "nome" da massa dágua selecionada toda em maiusculo

estilo_fonte = 'Condensed Italic'

tamanho_txt = calculado da seguinte forma:

CASE
WHEN "tamanho" < 770* ("escala" /1000)^2
THEN 6.0
WHEN "tamanho" < 2300* ("escala" /1000)^2
THEN 6.0
WHEN "tamanho" < 3600* ("escala" /1000)^2
THEN 7.0
WHEN "tamanho" < 5200* ("escala" /1000)^2
THEN 8.0
WHEN "tamanho" < 9800* ("escala" /1000)^2
THEN 9.0
WHEN "tamanho" < 16650* ("escala" /1000)^2
THEN 10.0
WHEN "tamanho" < 25000* ("escala" /1000)^2
THEN 12.0
WHEN "tamanho" < 36000* ("escala" /1000)^2
THEN 14.0
ELSE 16.0
END

justificativa_txt = 2
espacamento = 0
cor = '#00a0df'
carta_simbolizacao = combo box de carta de simbolização (Principal = 1, Mini = 2)

**Para carta ortoimagem tem mais atributos, talvez adicionar um combo box para definir se é Carta Topográfica ou Carta Ortoimagem e preencher os atributos de acordo**

- [x] **Botão: Rótulo de Rio**

É uma ferramenta de aquisição linha que adiciona na camada edicao_texto_generico_l preenchendo atributos.

São dois casos: 

linha de elemnat_trecho_drenagem_l selecionado com situacao_em_poligono = 1

texto_edicao = "nome" do trecho de drenagem

estilo_fonte = 'Condensed Italic'

tamanho_txt = calculado da seguinte forma:

CASE
WHEN "tamanho" < 80* "escala" /1000
THEN 6.0
WHEN "tamanho" < 120* "escala" /1000
THEN 7.0
WHEN "tamanho" < 160* "escala" /1000
THEN 8.0
ELSE 9
END

espacamento = 0

cor = '#00a0df'

carta_simbolizacao = combo box de carta de simbolização (Principal = 1, Mini = 2)

linha de elemnat_trecho_drenagem_l selecionado com situacao_em_poligono in (2,3)

texto_edicao = "nome" do trecho de drenagem em maiusculo

estilo_fonte = 'Condensed Italic'

tamanho_txt = calculado da seguinte forma:

CASE
WHEN "tamanho" < 65* "escala" /1000
THEN 6.0
WHEN "tamanho" < 80* "escala" /1000
THEN 7.0
WHEN "tamanho" < 100* "escala" /1000
THEN 8.0
WHEN "tamanho" < 120* "escala" /1000
THEN 9.0
WHEN "tamanho" < 160* "escala" /1000
THEN 10.0
WHEN "tamanho" < 200* "escala" /1000
THEN 12.0
ELSE 14.0
END

espacamento = 0

cor = '#00a0df'

carta_simbolizacao = combo box de carta de simbolização (Principal = 1, Mini = 2)

**Para carta ortoimagem tem mais atributos, talvez adicionar um combo box para definir se é Carta Topográfica ou Carta Ortoimagem e preencher os atributos de acordo**

Para maximizar a produtividade, seria interessante que o funcionamento fosse da seguinte forma:
- Clicar na posição central que se deseja inserir o rio
- Verifica qual é a drenagem mais próxima e se o nome é não nulo
- A ferramenta deve calcular o tamanho ideal da linha baseado no tamanho do texto calculado e no numero de caracteres do nome
- Criar uma copia simplificada da linha do tamanho correto, com o centro naquela posição clicada e paralela a linha selecionada.

- [x] **Botão: Alternar posição do rótulo**

Altenar o atributo label_x e label_y das feições selecionadas na camada ativa de forma que a posição do texto faça um ciclo nas posições de quadrantes em torno da feição.

Topo Direito > Topo Esquerdo > Inferior Direito > Inferior Esquerdo > Topo > Direita > Esquerda > Inferior

Distancia de 0,4 mm.

Erro para o usuário se a camada ativa não tiver o atributo  label_x e label_y.

**Comment by dinizime** [comment]
https://gist.github.com/pedro-mar/74727f4724c6d3b3c512981aa83e54be

**Comment by elitonfilho** [comment]
Features implemented at 4ba9753, testing is required

**Comment by dinizime** [comment]
Botão: Alternar visibilidade - OK
 Botão: Alternar justificativa do texto - OK

 Botão: Alternar posição do rótulo
Os valores de label x e label y tem que ser em relação as coordenadas do ponto. E também depende da escala (pela distância estar em milímetros).
Assim, primeiro calcula 0,4mm na escala que está definida no combo box e depois cicla pelos label x e y somando esse deslocamento mais a coordenada do ponto.

**Comment by elitonfilho** [comment]
Modificações sugeridas foram implementadas em 9048e8f, a serem testadas

**Comment by dinizime** [comment]
Botão: Alternar posição do rótulo
Devido a âncora estar no canto inferior esquerdo tem que compensar no calculo.
Como isso depende do atributo que é usado para rotular e o tamanho da fonte tem que fazer um dicionário que guarda essa informação para cada camada.

**Comment by dinizime** [comment]
De forma geral adicionar um refresh no canvas após utilizar a ferramenta para não precisar mexer na tela.

Botão: Inserir Identificador Trecho Rodoviário
Adicionar a opção inicial no combo box para escolher sigla (ou ja deixar o combo box aberto)
A jurisdição não pode ser puxada do atributo da feição e sim da própria sigla (BR federal e outros casos estadual)
