### ISSUE TITLE
Ferramentas de edição para carta topográfica e carta ortoimagem

### ISSUE THREAD

**Issue by dinizime** [1cgeo/plugin_edicao#19]
### Ter um combo box a mais para diferenciar o uso em carta ortoimagem e carta topográfica.

- Alternar visibilidade, alternar justificativa, alternar rótulo, símbolo idt tr rodoviario funcionam da mesma forma para carta ortoimagem e topográfica.

- Simbolo Vegetação é somente para carta topográfica, apresentando uma msg pro usuário se o combo box não estiver configurado para Carta Topográfica.

- Copiar para texto genérico de edição: Os valores atuais são para carta topográfica. Adicionar os seguintes valores para carta ortoimagem:
Linha
texto_edicao - nome
estilo_fonte - 'Condensed Italic'
tamanho_txt - 10
espacamento - 0
cor - '#ffffff'
cor_buffer - '#000000'
tamanho_buffer - 1
carta_simbolizacao - conforme combo box

Ponto
texto_edicao - nome
estilo_fonte - 'Condensed Bold'
tamanho_txt - 10
justificativa_txt - 2
espacamento - 0
cor - '#ffffff'
cor_buffer - '#000000'
tamanho_buffer - 1
carta_simbolizacao - conforme combo box

- Ferramenta de rótulo de lago: Os valores atuais são para carta topgoráfica. Adicionar o seguinte valor para carta ortoimagem:

texto_edicao - mesmo que na carta topográfica
estilo_fonte - 'Condensed Italic'
justificativa_txt - 2
espacamento - 0
cor - '#ffffff'
cor_buffer - '#00a0df'
tamanho_buffer - 1
carta_simbolizacao - conforme combo box
tamanho_txt - mesmo que na carta topográfica

- Ferramenta de rótulo de rio: Os valores atuais são para carta topgoráfica. Adicionar os seguintes valores para carta ortoimagem:

createFeatureA
texto_edicao - mesmo que na carta topográfica
estilo_fonte - 'Condensed Italic'
espacamento - 0
cor - '#ffffff'
cor_buffer - '#00a0df'
tamanho_buffer - 1
carta_simbolizacao - conforme combo box
tamanho_txt - mesmo que na carta topográfica

createFeatureB
texto_edicao - mesmo que na carta topográfica
estilo_fonte - 'Condensed Italic'
espacamento - 0
cor - '#ffffff'
cor_buffer - '#00a0df'
tamanho_buffer - 1
carta_simbolizacao - conforme combo box
tamanho_txt - mesmo que na carta topográfica

### Mudar o tamanho da fonte para carta mini

Quando carta mini for selecionada o tamanho da fonte é alterado da seguinte forma: (tanto para carta topográfica quanto para carta ortoimagem)

Copiar para texto genérico de edição Linha: 4.5
Copiar para texto genérico de edição Ponto: 4.5
Ferramenta de rótulo de lago: 4.5
Ferramenta de rótulo de rio tipoA: 4.5
Ferramenta de rótulo de rio tipoB: 4.5

**Comment by elitonfilho** [comment]
Commits 4e9dd18f79228a933b653e7ed10452fd8a5a5fa6 and f85355164192ffe1ca6634a0951270616725bce3 addressing this issue
